[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Ces variables seront remplacées par les variables d'environnement Netlify
  VITE_USE_SUPABASE = "false"
  VITE_USE_MOCK_DATA = "false"
  VITE_API_URL = "https://gestionprojetsmt.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://gestionprojetsmt.onrender.com https://obdadipsbbrlwetkuyui.supabase.co wss:;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
